// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SriCare.Core.Persistence;

#nullable disable

namespace SriCare.Core.Persistence.Migrations
{
    [DbContext(typeof(CoreDBContext))]
    [Migration("20241226174140_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SriCare.Core.Domain.Roaming.Roaming", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activate")
                        .HasColumnType("boolean");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Roaming", (string)null);
                });

            modelBuilder.Entity("SriCare.Core.Domain.Roaming.RoamingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CallQuota")
                        .HasColumnType("integer");

                    b.Property<int>("DataQuota")
                        .HasColumnType("integer");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RoamingId")
                        .HasColumnType("uuid");

                    b.Property<int>("SMSQuota")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Validity")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoamingId");

                    b.ToTable("RoamingPlans");
                });

            modelBuilder.Entity("SriCare.Core.Domain.Roaming.RoamingPlan", b =>
                {
                    b.HasOne("SriCare.Core.Domain.Roaming.Roaming", "Roaming")
                        .WithMany("RoamingPlans")
                        .HasForeignKey("RoamingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roaming");
                });

            modelBuilder.Entity("SriCare.Core.Domain.Roaming.Roaming", b =>
                {
                    b.Navigation("RoamingPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
